### ISSUE TITLE
Question on error 000732 file not supported

### ISSUE THREAD

**Issue by ssday** [dtarb/TauDEM#104]
I have received this error using both the ArcGIS toolbox interface and the command line.  The file is a .tif and is only 1.9 GB.  I have been able to run other smaller DEMs (about 140 mb) without any problem.  Is there something I should be modifying to account for the larger DEM?  The documentation suggests that I should be able to run DEMs up to 4GB, but that is the only variable I can find that seems like it should make a difference in how the file is supported.

**Comment by dtarb** [comment]
Sorry to be slow in replying.  I need a few more details to know what the problem is.  Error 000732 is probably coming from the ArcGIS python script interface, so you should try run the program from the command line (see http://hydrology.usu.edu/taudem/taudem5/documentation.html documentation on using the command line).  This would remove one layer of potential problems.  You also need to make sure your computer has enough memory.  Roughly 4 times the file size is needed.  If the file is a format that GDAL can read (not limited to .tif) you should not need to do anything special to work with it, and you should even be able to run larger than 4 GB.
