### ISSUE TITLE
Unicode decode error and problems with downslope influence

### ISSUE THREAD

**Issue by CristinaGordo** [dtarb/TauDEM#111]
I'm having problems with execute all the tools from the lastest version of TauDem.

And i get all the time this message in every single tools that i try to use:

![image](https://cloud.githubusercontent.com/assets/25113254/21951636/614fdf4c-da01-11e6-97e2-d925d4ea177b.png)

I have also another problem not related to this one. I want to know  to calculate Infinity Downslope Influence with the latest TauDEM version?

Because the command was present until version 3.x but now disappeared and I don't know if it was renamed or simply removed.

And i cannot use the taudem 4.0.6 because it causes a debug error.

Thank you.

**Comment by dtarb** [comment]
The error that you are getting seems to be from the python code that is reading the text returned by the command line function it calls.  To debug I suggest you run TauDEM from the command line.  Open a command prompt and type in (or copy and paste) the command line text from your message window

> mpiexec -n 8 pitremove ...

Hopefully this will show why the function is not running and what the python is having trouble decoding.  Refer to http://hydrology.usu.edu/taudem/taudem5/TauDEM53CommandLineGuide.pdf to learn more about command line use.

Downslope influence is a special case of Dinfinity Contributing area with weight grid input with weight values of 1 for the grid cells that you want to evaluate the influence of.  So you can use Dinfinity Contributing area to get the same result.

**Comment by CristinaGordo** [comment]
Thank you for the quick feedback.

I type messange in the command line text was you suggest and i get this message error.

![image](https://cloud.githubusercontent.com/assets/25113254/21956457/1b8a1644-da79-11e6-9768-ddbddd2de663.png)

**Comment by dtarb** [comment]
This indicates to me that something is wrong with your MPI installation, or its path on your system.  I suggest checking the following
> where mpiexec
You should get the answer "C:\Program Files\Microsoft MPI\Bin\mpiexec.exe"
> where smpd
You should get the answer "C:\Program Files\Microsoft MPI\Bin\smpd.exe"
> where areadinf
You should get the answer "C:\Program Files\TauDEM\TauDEM5Exe\AreaDinf.exe"

> path
You may get a lot of folders, but look for "C:\Program Files\Microsoft MPI\Bin\" to be near the beginning and "C:\GDAL;C:\Program Files\GDAL;C:\Program Files\TauDEM\TauDEM5Exe;" to be later.  These are the ones that TauDEM uses.

If you get anything else for any of these it may indicate a different (possibly conflicting) version of the software on your system, or path not found.

There may also be a permissions issue with smpd, so if all components appear to be found, check the firewall and perhaps try run as administrator.

The original error that you received "ascii codec cant decode" appears to be due to non ascii characters in the message being generated.  This is a limitation that TauDEM has (with internationalization of the code) that I would like to fix in the future.  But this is not stopping the program from running, it is just interfering with the display.  The characters in the text RPC ... est ... dispon ... appear to be non ASCII and may be triggering this message.

**Comment by CristinaGordo** [comment]
Thank you so much i think the problem is solved!

I don't know why but maybe when i tried to install a latest version of TauDEM, when package came also a MPI version from 2012, and this as causing a conflict.

Best regards,

Cristina Gordo

**Comment by dtarb** [comment]
Great!
