### ISSUE TITLE
Question:  Where is Model Builder tbx?

### ISSUE THREAD

**Issue by sjskhalsa** [dtarb/TauDEM#117]
I just installed and have running TauDEM537. Reading the tutorial it references the Model Builder, but I can't find this on the current downloads page.  Where is it?

**Comment by dtarb** [comment]
There is a link to the toolbox in http://hydrology.usu.edu/taudem/taudem5/downloads5.1.html, specifically http://hydrology.usu.edu/taudem/taudem5/TauDEMModels_51.tbx.  However you may need to fiddle quite a lot to get this to work.  I have had trouble configuring the toolbox in a way that it can be distributed and work on multiple computers and work with newer versions of ArcGIS, so have basically given up on trying to maintain a smoothly functioning distributable version which is why it it not on the latest release site.  If you need to string together TauDEM functions the most efficient way is in a script file (windows command prompt), but that is not quite as elegant.

**Comment by sjskhalsa** [comment]
Understood.  Actually, I guessed this was the case.  OK, no prob. I can script the individual .py routines.  Thanks for responding!
