### ISSUE TITLE
Question: Possible to define watersheds from D-infinity?

### ISSUE THREAD

**Issue by sjskhalsa** [dtarb/TauDEM#118]
No functions for defining watersheds from D-infinity accumulation and stream grids?

**Comment by dtarb** [comment]
This is not possible with TauDEM.  You can use D-Infinity accumulation as an input for stream thresholds, but watersheds require a single determination of whether a grid cell is in or out of a watershed.  When flow goes in multiple directions, as with D-Infinity this becomes uncertain.  One can go with the largest proportion, but then that results in the same thing as single flow direction D8 that is used to delineate watersheds.

**Comment by sjskhalsa** [comment]
Thanks for the explanation. A grad student here at CU has given me the locations where she sampled drinking water along the Gokyo Valley on the main trekking route to Everest Base Camp and wants to know the contributing area. Some are at very small streams, perhaps spring fed. When using the D8 some of the associated accumulation areas are so small as to be unrealistic if based on precip and snowmelt alone, so I guess it's coming from groundwater. I thought I could get a more precise accumulation area with D-infinity.

**Comment by dtarb** [comment]
You may be able to get the answer you need from some D-Infinity TauDEM functions without defining a crisp watershed.  You could create a grid of the cell (or cells) representing points where water was sampled and use that as input to the D-Infinity Upslope dependence function.  This will return a grid giving the proportion each grid cell contributes to these destination cells.  Grid cells that have a value of 1 contribute all their flow to the destination cells.  As the fraction varies between 1 and 0 the contribution is more or less.  So this would amount to a fuzzy edged watershed.  Information on how to use D-Infinity Upslope dependence is at  http://hydrology.usu.edu/taudem/taudem5/help53/DInfinityUpslopeDependence.html.

You can also get similar information with D-Infinity contributing area and a shapefile of points at your sampling points.  Contributing area will only be evaluated for grid cells that contribute to the input points, though unlike D-Infinity Upslope dependence the proportional contribution is not given (which is why we developed D-Infinity Upslope dependence).

**Comment by sjskhalsa** [comment]
I'm with ya. I already ran the D-infinity Distance Upslope function and was trying to figure out where to go from there.  You've been very helpful. More than can be said for many free tools.  And don't get me started on ArcHyrdo tools. What a headache working with those!
