### ISSUE TITLE
Question：How to calculate TWI based on D8 algorithm

### ISSUE THREAD

**Issue by houzw** [dtarb/TauDEM#121]
I'm new to TauDEM,  I found there is a command [TWI](http://hydrology.usu.edu/taudem/taudem5/help53/TopographicWetnessIndex.html) to calculate Topographic Wetness Index, but I have no idea how to get SCA use D8, and confused with the following words:
>*If D8 or some other contributing area evaluated using the number of cells is used here it should first be scaled by cell size to give specific catchment area in length units.*

Any instruction or example about this? 
Thanks

**Comment by dtarb** [comment]
Sorry about the confusion.

D8 refers to the single direction flow model for representing a topographic flow field that has grid cells draining to only one of their neighbors.  This is as opposed to the Dinfinity flow model that proportions flow between multiple neighbor grid cells.  In TauDEM D8 flow directions are calculated using the D8 Flow Directions (D8FlowDir) function.  See http://hydrology.usu.edu/taudem/taudem5/help53/D8FlowDirections.html, where there is a picture for how these flow directions are defined.  See https://wiki.cigi.illinois.edu/display/DOC/Dinfinity+Specific+Catchment+Area, where there is a picture for the Dinfinity flow model.

SCA refers to specific catchment area which is defined as contributing area per unit contour width.  In TauDEM it is suggested that slope and specific catchment area inputs to the TWI function come from the Dinfinity Flow Direction (DInfFlowDir) and Dinfinity Contributing Area (AreaDinf) functions respectively.  The result from AreaDinf is already expressed in the length units of SCA [(contributing area length^2)/(width length) has units length (e.g. m)].  

It is also possible to evaluate contributing area using the D8 representation of the topographic flow field.  In TauDEM this would be done with the D8 Contributing area (AreaD8) function.  However this (unless a weight field is used) reports its results as a count of grid cells, not ready for use in a TWI calculation.  To use in TWI the result from AreaD8 should be scaled to length.  One way to do this is to multiply by cell size following the argument that
Area = number of cells * cell size ^2
Contour width = cell size
Specific catchment area = Area/Contour width = number of cells * cell size.

Note that there are subtleties in these calculations that should be considered.  
- The evaluation of TWI = ln(specific catchment area/slope) is the log of a quantity with length dimensions.  Logs of quantities are typically treated as dimensionless, but the units of length matter for the result, so I prefer to indicate the units as log-length (e.g. ln(m)).  Unit conversions for this quantity are tricky, and comparisons require consistent units, which is why when using D8 the scaling by length is needed.
- The contour width used in the definition of specific catchment area may depend on the flow direction.  Use of cell size is an approximation.  See #72 for how TauDEM may be changed when we get a chance to correct this.

**Comment by houzw** [comment]
@dtarb Many thanks

**Comment by violleTolorza** [comment]
So, if we prefer a steepest descent algorithm, it is best to scale the D8 Contributing Area than to use the D-inf Contributing Area?
thanks in advance your response

**Comment by dtarb** [comment]
The TWI function can take as input an grids and really only evaluates ln(area grid/slope grid).  You can input specific catchment area calculated using any method you like for area grid.  If you use the result from AreaD8 you should multiply by cell size to get it into area per unit contour width units, as without this it is in number of cells units.
