### ISSUE TITLE
streamnet producing single watershed 

### ISSUE THREAD

**Issue by KittelC** [dtarb/TauDEM#133]
I am having trouble using Taudem 5.3.7 both from the cmd and through QGIS 2.18.9. 

I manage to get the order and stream shapefile (although the numbering of stream ID's is slightly odd and skips several numbers) but the "-w" output, or watershed file, only contains a single watershed and not subwatersheds for each stream segment. I used the compiled Windows 64bit installer and installed both MPI v.8 and GDAL for python without luck. All other TauDem functions appear to work fine.

**Comment by dtarb** [comment]
QGIS may be intentionally giving you only a single watershed.  See http://hydrology.usu.edu/taudem/taudem5/help53/StreamReachAndWatershed.html.  TauDEM has the option to produce a single watershed, or subwatershed for each stream segment.  The "-sw" flag is specified on the command line to indicate single watershed.  Not specifying "-sw" from the command line should give you subwatersheds.  QGIS may always be setting this or there may be an element on the interface that you can control this (sorry I am not familiar with the QGIS interface).  

The numbering skips because of parallel processing.  Each processor assigns numbers unique to it, and when there are a different number of stream segments starting in each processor partition (as there almost always are, it would be highly unlikely to get exactly the same number of streams starting in each partition) the numbers may skip.  There is no requirement or assumption in TauDEM that the numbers are sequential.  But this does mean that other programs using the TauDEM identifiers should not assume they are sequential.

**Comment by mach0** [comment]
Hi!
I am not sure if I know exactly what you mean but there is a switch in QGIS Taudem where you can select between single watershed and subwatersheds.
It is called "Delineate Single Watershed" and is selected by default. So that might explain why you only get a single watershed.
Deselecting it results in subwatersheds.
Hope this helps!

**Comment by KittelC** [comment]
Thank you for both your replies! You pointed me in the right direction: 

By default, the switch in QGIS is off - meaning there is the option to create the single watershed, but it is unchecked. However, I found out that by checking the box, subwatersheds were created, meaning the switch had the opposite effect. 
It turns out, the -sw flag is added to the command line by QGIS when the box is unchecked but removed when the box is checked. By default, the "-sw" option is defined as "False" by QGIS - however this prompts taudem to create one watershed.  The problem lies in how QGIS defines boolean parameters in the Taudem plugin: if no value is given, it appends the parameter name, in this case the "-sw" flag.
