### ISSUE TITLE
Problem with output when calculating D-Infinity Contributing Area from the Command Prompt

### ISSUE THREAD

**Issue by rcammarere** [dtarb/TauDEM#142]
While going by the reference for calculating Specific Contributing Area at http://hydrology.usu.edu/taudem/taudem5/TauDEM51CommandLineGuide.pdf, I was able to get an output file (ScaRaster.tif), but the range of values is 0 - 6.28319 (which looks like angular values in radians which are in the DInfFlowDirRaster.tif input file that I used).
To perform a test run, I copied the input (D-Inf Flow Direction) raster into the folder with the AreaDinf.exe file.  This is what the line looked like, that I typed in at the command prompt:
    C:\Program Files\TauDEM\TauDEM5Exe>AreaDinf -ang DInfFlowDirRaster.tif -sca ScaRaster.tif
Results after running at command prompt:
    AreaDinf version 5.1.2
    This run may take on the order of 1 minutes to complete.
    This estimate is very approximate.
    Run time is highly uncertain as it depends on the complexity of the input data
    and speed and memory of the computer. This estimate is based on our testing on
    a dual quad core Dell Xeon E5405 2.0GHz PC with 16GB RAM.
    Processors: 1
    Read time: 0.028368
    Compute time: 0.269122
    Write time: 0.026778
    Total time: 0.324268

When I ran the D-Infinity Contributing Area TauDEM tool in ArcMap, using this same D Infinity Flow Direction input raster file (DInfFlowDirRaster.tif), I got an output file that contained the desired results (range of 26.1639 to 5782.23).  I checked the output window when running the tool, and the syntax appears to be the same.

Therefore, my question is, am I doing something wrong at the command prompt? How do I run this at the command prompt, and get contributing area type results?
Thanks.

**Comment by dtarb** [comment]
What you are doing should work and I do not know what is going wrong.

Try copy just the ScaRaster.tif file (no pyramids or other auxiliary files) into a different folder then load into ArcMap.  Sometimes ArcMap renders rasters using an old color scheme.

Usually we run the functions using MPI, with a command like
mpiexec -n 4 AreaDinf -ang DInfFlowDirRaster.tif -sca ScaRaster.tif
This takes advantage of parallel/multi core capabilities.  The 4 should be a number close to the number of cores you have.  What you did above should be equivalent to the number of cores being 1, but this should not change the data being output.

Another possible concern is write permissions in the C:\program files folder.  Typically regular users are not permitted to write files here so it is better to run from the command line writing elsewhere.  But again I can not see how this could cause errors in the data output.

**Comment by rcammarere** [comment]
Thanks so much for responding David.



I've read your response, and I just wanted to let you know what I've learned recently . . .



Although I can bring the D-Infinity Flow Direction raster that I create, into ArcMap, and it shows up in the right place on the map (it has a spatial reference and the proper extents), I guess it's not really considered a GeoTiff (because I can view it with any photo rendering software).



Therefore, I exported the D-Inf Flow Dir Raster tif file in ArcMap to a TIFF.  This caused a world file to be created along with the new tif.  Then I used that new version of "DInfFlowDirRaster.tif" that was created in ArcMap as input and ran AreaDinf at the command prompt again.  This time the sca output came out correct.  From this I believed that creating a world file to go with the DInfFlowDirRaster.tif  (that is created by using pygeoprocessing), might resolve this issue.  However, it didn't.  The world file (that I created programmatically in C#) looks exactly the same as the one created by exporting the data to a TIFF in ArcMap, so the world file can't be the issue.



Now I am looking into what exactly is done by ArcMap when exporting data to a tif.



BTW, I did use mpiexec when running from the command prompt as well, but as long as I used the D-Infinity Flow Direction raster that I created by using pygeoprocessing, it didn't give the desired result.



I have tried to run it from my C# application (which has the inputs and outputs in a different location than the executable) but the output comes out the same as the input.



To give you the shortened version of all that, I know that the issue has to do with the input raster, so I'll keep working on it.



Regards,

Renee

________________________________

**Comment by dtarb** [comment]
I do not know exactly what is going on, but I think that this is most likely a display problem.  I do not think there is any way TauDEM could sometimes write the correct incorrect information to the output file and sometimes incorrect information.  I think the correct information is always being written, but that display is being confused by other files such as the world file.

I just noticed that you are using TauDEM 5.1.2 version.  This was before the program was changed from using its own code to read and write tif files to GDAL.  I suggest you switch to the latest version that uses GDAL.  The GDAL library may do a better job of managing the metadata of the raster file in a way that GIS displays are expecting. The earlier version had limitations in some of the types of geotiff files files it could read (it could not read compressed files, or files bigger than 4 GB among others).

I know that the 5.1.2 TauDEM version only reads content from and writes content to the *.tif file.  Other files associated with grids that various GIS systems use (like world file) are not touched at all by TauDEM, so I do not think that anything you do with world files will change the TauDEM result.  But it may change the way things are displayed in what you do following.  I cannot definitively make the same statement about not using world files for the later version of TauDEM, because GDAL may look at these files, but since you are using version 5.1.2 I think that TauDEM results are unlikely to be the problem and that what is in TauDEM results is unrelated to world files.

The TauDEM ArcGIS interface (written in Python) constructs a command line command (like mpiexec -n 4 AreaDinf -ang DInfFlowDirRaster.tif -sca ScaRaster.tif) that you will see in the ArcGIS tool output.  Once this completes, it uses an ArcGIS statistics function to calculate statistics on the result.  This results in creation of auxilliary files by ArcGIS (*.tif.xml and *.tif.aux.xml).  If you are running from a command line and then just load the results into ArcGIS it can occur that the display may not show the range of the data properly due to statistics not being calculated.  An ArcGIS calculate statistics function on the result can fix this.
