### ISSUE TITLE
Memory allocation error during partition - how to solve?

### ISSUE THREAD

**Issue by auniqueusernameisnotavailable** [dtarb/TauDEM#147]
I am trying to run through a work flow that has worked fine for several previous projects. On this particular project I get the following error any time I try to run any of the TauDEM tools.

"Memory allocation error during partition initialization in process 0."

I have found that the ArcGIS tools (e.g. fill) seem to work fine, but I cannot get the specific TauDEM tools to work.

I have tried clearing memory, restarting the computer, and expanding the virtual memory. I am unclear how else to proceed.

![message](https://user-images.githubusercontent.com/31519168/32295089-d2628b48-bf0d-11e7-84bc-0c9186639fc8.png)

**Comment by dtarb** [comment]
I believe this is an out of memory problem.  You have 73116*51188 = 3.7 x 10^9 grid cells, each of which takes 4 bytes resulting in 15 x 10^9 bytes for a single Grid.  Pitremove effectively uses 4 grids, so you are asking for 60 x 10^9 = 60 GB of RAM.  Unless your computer has this much RAM it will fail.

There is another cosmetic error on display.  NCells is showing up as negative.  That is likely because the variable being used to print it is 4 byte signed integer and the number of cells overflows this.

You may be able to eke more out of your computer if you use multiple processes.  To do this you would use a command like
mpiexec -n 8 Pitremove -z DEM.tif -fel DEMF.tif
This is the preferred way to run anyway as it takes advantage of parallelism.

The memory used by each process will be less, but there will be multiple processes that will swap in and out of RAM.  If you are only modestly over your physical RAM size this works, but if you are significantly over your physical RAM the repeated swapping slows the system to a crawl making completion essentially impossible.

Sorry this is not better news.

**Comment by auniqueusernameisnotavailable** [comment]
Thank you, that is very helpful.

**Comment by dtarb** [comment]
We have explored this approach, and have a paper describing it for pitremove in Yıldırım, A. A., D. Watson, D. Tarboton and R. M. Wallace, (2015), "A virtual tile approach to raster-based calculations of large digital elevation models in a shared-memory system," Computers & Geosciences, 82: 78-88, http://dx.doi.org/10.1016/j.cageo.2015.05.014.  http://hydrology.usu.edu/dtarb/Yildirim_virtual_tile_paper_author_version_2015.pdf.

However, as this is only for pitremove it is not part of TauDEM.  Work in this area is certainly needed.
