### ISSUE TITLE
AreaDinf problem with outlet points

### ISSUE THREAD

**Issue by chdemars** [dtarb/TauDEM#164]
I am trying to use AreaDinf to find the contributing watershed to a single point using the -o flag.

If I don't use the -o flag, I get a valid raster image. If I do use the -o flag (for a shapefile of one or many points), I get an empty raster.

The weird thing is that this was working earlier. The only thing that has changed on the computer is adding more ram. In case that might have been the problem, I uninstalled TauDEM and all support programs and reinstalled to no avail.

I'm running it on a Windows 7 computer using the command line tools and the 5.3.7 complete installer. I have example data if there is any interest, but the rasters are large.

Is there any way to get debugging information out of TauDEM to see where it might be failing? The info printed to the console indicates everything is working fine, but I don't see a verbose tag or anything similar to get more details.

**Comment by dtarb** [comment]
There are -v flags in some functions, but not AreaDinf.  I would be very surprised if adding RAM made a difference or if uninstalling and reinstalling was the issue.

The most likely problem is that the outlet point is at a location where AreaDinf cannot be evaluated.  This may be due to it being no data because of edge contamination (the -nc flag may fix this) or due to being out of the domain (due to being in a different coordinate system).

If these do not sort it out, feel free to send me the data (using something like Google Drive or Drop box if too big to email)

**Comment by chdemars** [comment]
It turns out it was a projection error.

Apparently neither the EPSG nor the proj.4 string from using gdalsrsinfo on the raster was good enough to properly project the point. I wound up having to reproject the rasters instead. Hopefully all the reprojecting doesn't introduce any significant errors.

Thank you for your response.

**Comment by dtarb** [comment]
Glad it worked out.
