### ISSUE TITLE
Can I tell which input cell is contributing to which streamline network?

### ISSUE THREAD

**Issue by WindingWinter** [dtarb/TauDEM#178]
I can generate the streamline network via [streamnet function](http://hydrology.usu.edu/taudem/taudem5/help53/StreamReachAndWatershed.html); the output of the streamline network can be read from `coordfile` and `treefile`. 

But what about which cell of the terrain that contributes to a particular streamline? And how to obtain the portion of upstream cells that contribute flow to each cell? If I understand the above document correctly, this information is encoded in `wfile` ( with the file extension `.tif`) and (or?) `netfile` ( with the extension `.shp`). 

If this is so, then I'm unclear about how to parse the information. I would want to use my own rendering engine to show which streamline/cell is receiving flow contribution from which cell, which is why I would need a way to decode the relevant output files. 

Generating something like this (where the legend denotes the number of cells contributing flow to it) 
 in my own rendering software, with my own file format, would be my aim:

![Image of flow contributing cell](https://i.stack.imgur.com/1AfsS.png)

**Comment by dtarb** [comment]
The streamnet function outputs the following files
*tree.dat
*coord.dat
*w.tif
*net.shp
The suffixes - not file extensions are the TauDEM defaut names, and * represents the prefix name part that would typically inherit from your data

The formats are documented at http://hydrology.usu.edu/taudem/taudem5/help53/DataFileFormatsAndFileNamingConventions.htm
*w.tif (wfile) is an integer raster that encodes for each cell the identifier of the watershed that this grid cell is a member of.
*net.shp is an ESRI shapefile (actually comprised of *.shp, *.dbf, *.shx, *.prj etc) that has an attribute table with columns LINKNO and WSNO.  WSNO is the watershed number and serves as a cross reference to *w.tif.  So grid cells numbered X in *w.tif drain to the stream reach with watershed number WSNO in *net.shp.
In *net.shp there is also a unique number LINKNO.  (In the example I looked at LINKNO is identical to WSNO.  It may be a historical accident that there are two columns with the same thing, or there may be cases where they are different.  I am not sure now).  LINKNO is also used in *tree.dat (first column).  *tree.dat and *coord.dat represent partial results that streamnet outputs prior to *net.shp.  If you establish that WSNO and LINKNO are identical then you could use it to relate directly to *tree.dat information.  Otherwise to relate *tree.dat to *w.tif you will need to go through *net.shp attribute table.

With the D8 flow model that is used by streamnet, each grid cell drains directly to one and only one link (stream segment) in the network (identified by WSNO/LINKNO).  However following down flow directions from any grid cell after a stream is encountered (andWSNO identified) one can continue down into other stream reaches in the stream network.  The columns DSLINKNO and USLINKNO1 and USLINKNO2 in the *net.shp attribute table provide down and up connectivity, so you can traverse the network and from any particular reach identify all upstream reaches and their watersheds of you want to locate all the watersheds that drain to any particular location.  

The outputs from the aread8 function give the number of grid cells draining to any one grid cell.  If this function is run with a shapefile input, it will only compute for grid cells upstream of points in that shapefile.

Look also at gagewatershed in http://hydrology.usu.edu/taudem/taudem5/documentation.html.  This gives additional flexibility in identifying the watersheds draining to specific points.

Hopefully this gets you towards what you want.

**Comment by nsoonhui** [comment]
Thanks for your explanation, 

I notice that there can only be 2 upstream link nodes  ( denoted by USLINKNO1 and USLINKNO2) per every LINKNO. But a LINKNO should be able to have more than two upstream links right? What happens if there are more than two upstream links for every LINKNO?

Since LINKNO is unique in `*net.shp` file, what happens if there are two or more WSNO linked to a LINKNO ( I can certainly imagine such scneario)?
