### ISSUE TITLE
Option to write the output to memory stream instead of files

### ISSUE THREAD

**Issue by WindingWinter** [dtarb/TauDEM#181]
Is it possible to have an option to write the output to memory stream ( instead of files currently)? This would be useful if we want to call taudem as libraries instead of as command line programs ( #174 )

**Comment by dtarb** [comment]
It may be possible.  You would need to change the code.  The grid file writing is done in tiffIO.cpp tiffIO:;write function (so named because originally this was only tiff files although now it will handle any files that GDAL can handle).  You can see in this function the GDAL functions being used to write files.  There is information at http://www.gdal.org/frmt_gtiff.html about streaming so you would need to figure out how to change the inputs to the GDAL functions TauDEM is using to enable this.  Good luck.
