### ISSUE TITLE
Different Results depending to number of Processors, wrong Output of AreaDinf

### ISSUE THREAD

**Issue by phuongduyta** [dtarb/TauDEM#185]
Hi Prof. Tarboton, 

First of all thank you very much for your contribution to the world of hydrology and for the nice program also.

As I tested the program with command line, I figured out that for my test raster data (5x5), the results of _DinfFlowdir_ will not be unique depends on the number of cores I choose.
If I choose the number of processors as 1, I will have Output-Slope- and -Angle-Rasters with the size of 3x3.
If I choose the number of processors as default (8) I will have another row at the top of the outputs (make it 4x3) with very strange values of angle and slope. (slope up to 29841095995757028291968702891870388224).

Furthermore if I use the _AreaDinf_ function (with no other optional options) for the first created angle raster (3x3), I get an empty raster which should not be. (no matter if 1 or 8 processors).

I attached the input as well as the outputs so maybe you could help me with that.

I would appreciate it very much.

Thank you

Phuong

[Test_TAUDEM.zip](https://github.com/dtarb/TauDEM/files/2297952/Test_TAUDEM.zip)

**Comment by dtarb** [comment]
I see two issues
1. Erroneous results when number of processes exceeds number of rows of data.
2. No data from areadinf.

Regarding 1, the problem is the partitioning of the domain into stripes.  The programs use a row based partitioning, so if say there are 20 rows in an input DEM and 8 processors 20/8=2.5 and the system will divide the DEM into some combination of 2 or 3 rows for each processor to work on.  Perhaps 2,3,2,3,2,3,2,3 which adds up to 20.  (I did not check the code to see the actual rule).  Here if there are only 5 rows but 8 processors, it will be trying to do something like 1,0,1,1,0,1,1,0, and I think it will have trouble when a partition gets 0 rows of data to process.  This is a bug, and I should figure out something sensible to do for very small datasets where the number of rows is less than the number of processors.  Until then, I suggest just using 1 processor for these small test cases.

Regarding 2, I think the no data for areadinf is edge contamination, as it occurs even with 1 processor.  See http://hydrology.usu.edu/taudem/taudem5/help/DInfinityContributingArea.html.  The most outside rows and columns of your 5x5 grid will have no data for flow direction because flow direction cannot be computed at an edge.  This leaves the inner 3x3 grid.  The outer rows and columns of this cannot be computed for contributing area because they touch grid cells with flow direction not known.  They will be no data.  This leaves just the middle 1x1 cell.  If any of the neighbors around it flow towards it, then it will get a no data value for contributing area because contributing area of the neighbors is not computable.

**Comment by phuongduyta** [comment]
Thank you very much for your comment.
I made some tests based on your explanations and can confirm them!

The issue can be therefore closed.
