### ISSUE TITLE
What are the essential fields in geotiff that I need to specify before I can use TauDEM?

### ISSUE THREAD

**Issue by WindingWinter** [dtarb/TauDEM#190]
I generate a TIN surface in C# ( using my own algorithm and data structure), and I would need to write it to a geotiff file before I can use the TauDEM library for further catchment delineation and catchment analysis. I will probably use a library such as LibTiff.Net in order to set the relevant geotiff fields and generate the geotiff file.

My question is, I believe that geotiff format contains many many fields, a lot of which are not essential for the TauDEM purpose.  

May I know what are the absolute essential fields in geotiff formats that TauDEM use?  Then I can just write those fields to generate a geotiff file for TauDEM consumption.

**Comment by dtarb** [comment]
You are correct that there are geotiff fields that are not essential.  However I am not exactly sure which are, because the GDAL library is used to read geotiff files.  Following is my best guess.

Look at the code starting at https://github.com/dtarb/TauDEM/blob/f927ca639a1834565a76cb3df5acbcd2909d6d0d/src/tiffIO.cpp#L92

I think you need at least fields that specify rasterXSize, rasterYSize and cell size in x and y dimensions (entries 1 and 5 in the GeoTransform array).  You may also need a no data value.  I think that the rest the program will manage without.

Following is a set of tags in a minimal geotiff file (without coordinate system) that I know works in TauDEM, however they may not all be necessary.  
```
ImageWidth (1 Short): 281
ImageLength (1 Short): 523
BitsPerSample (1 Short): 32
Compression (1 Short): Uncompressed
Photometric (1 Short): MinIsBlack
StripOffsets (75 Long): 978, 8846, 16714, 24582, 32450, 40318,...
SamplesPerPixel (1 Short): 1
RowsPerStrip (1 Short): 7
StripByteCounts (75 Long): 7868, 7868, 7868, 7868, 7868, 7868, 7868,...
PlanarConfig (1 Short): Contig
SampleFormat (1 Short): 3
33550 (3 Double): 
33922 (6 Double): 
42112 (86 ASCII): <GDALMetadata>   <Item name="LAYER_TYPE" samp...
42113 (25 ASCII): -3.4028234663852886e+038 
```

Note also that TauDEM does not require geotiff.  It works for other GDAL formats that the code in tiffio can read.  For example you could use an ASCII file of the form
```
ncols         5 
nrows         4 
xllcorner     0 
yllcorner     0 
cellsize      10 
NODATA_value  -9999 
25.4 26.1 27 28.6 27.7
25 26 26.4 27.9 27.4
25.1 25.8 26.8 28.6	27.6
27.5 28 27.7 30.6 28.3
```

**Comment by dtarb** [comment]
Yes.  Taudem works with this file.  The command
```
mpiexec -n 1 pitremove -z elev.asc -fel elevfel.tif
```
produces the elevfel.tif file output.  Both are here 
[elev.zip](https://github.com/dtarb/TauDEM/files/2633277/elev.zip)
