### ISSUE TITLE
D-infinite Transport limited accumulation returns no value on some cells

### ISSUE THREAD

**Issue by oddsss** [dtarb/TauDEM#253]
After using this tool, rivers with low heights have missing values. There are no missing data after calculating using the test data from TauDEM.
The output values range from 0-95,000. TauDEM test values are also in the order of 10,000. d But I have read several papers and found that their output values are very low not sure why.
![image](https://user-images.githubusercontent.com/56829532/230723509-30fed28d-111d-4e21-940e-abb7248aa488.png)

**Comment by dtarb** [comment]
From the picture above it looks like you are experiencing edge contamination.  This is more fully described [here](https://hydrology.usu.edu/taudem/taudem5/help53/DInfinityContributingArea.html).  You can turn off the checking for edge contamination at the risk of missing contributions from outside the domain of your data by using "-nc" in command lines or unchecking the box in the interface.  See the transport limited accumulation [documentation  ](https://hydrology.usu.edu/taudem/taudem5/help53/DInfinityTransportLimitedAccumulation.html)

**Comment by oddsss** [comment]
Thank you for your prompt reply. But I didn't check this option while I was doing it. I used the Taudem test data that you published, and its output was fine and consistent with your reference results.
I'm also confused because I saw that in the RUSLE-TLSD papers, the DEP output was very small, only a few hundred values. But whether it's test data or my own data, the output value is in the tens of thousands,

**Comment by dtarb** [comment]
The TauDEM test data is not clipped along the watershed boundary and does not produce edge contamination problems.  Your data appears to be clipped along a watershed boundary, so to avoid the no data streaks you have to disable the edge contamination checking.  This is risky because you will not know if there is any error associated with how your data was clipped.  I do not know which RUSLE-TLSD papers you are referring to, but my guess is that to understand how they and the output from this function relate, you will need to carefully work through the units and spatial areas being used in each calculation.

**Comment by oddsss** [comment]
Thank you Professor for your patient reply. I will check the relevant based on your response. When I find a problem, I will let you know as soon as possible. Have a nice day.

**Comment by oddsss** [comment]
I performed the mask extraction and resampling of the data in the study area beforehand, and then performed the D-TSLD calculation afterwards, and the images were not missing. But I still don't know why the value of the result is such large.
