### ISSUE TITLE
No BIGTIFF support in tiff file creation because of geotiff compression support

### ISSUE THREAD

**Issue by ahmetartu** [dtarb/TauDEM#49]
Currently, TauDEM is failing to create tiff file larger than 4 GB. As described at [GeoTIFF Gdal Page](http://www.gdal.org/frmt_gtiff.html), if the compression is used in geotiff creation, BIGTIFF must be passed explicitly to papszOptions in GDALCreate function. The code in tiffIO::write function at tiffIO.cpp to fix that issue should be:

`
// if the extension is tiff, set bigtiff to true

if (index == 0)
papszOptions = CSLSetNameValue( papszOptions, "BIGTIFF", "YES");

`

where that code can be inserted after line in tiffIO.cpp:

`papszOptions = CSLSetNameValue( papszOptions, "COMPRESS", compression_meth[index]);`

**Comment by dtarb** [comment]
@ahmetartu I am concerned that this would seem to force all tiff files to BIGTIFF and whether this would make them incompatible in some cases.  I wonder if we need a calculation to see if this falls in the BIGTIFF range before setting this option.  This calculation would use the totalX, totalY and datatype variables.  I am suggesting we do this ourselves because reading the Gdal page mentioned it appears that the BIGTIFF = IF_NEEDED setting does not work with compression.  If you have time to make and test this change it would be a welcome fix.

**Comment by dtarb** [comment]
Suggested fix for this:
1. Add option to specify BIGTIFF when file is bigger than 4 GB (as computed using totalX * totalY * cellbytes/1e9).
2. Add .tiff (with two ff's) as a file write option with the convention that these files will not be compressed.

**Comment by dtarb** [comment]
Fixed at v5.3.4
