### ISSUE TITLE
mpiexec can't find gdal111.dll - R

### ISSUE THREAD

**Issue by fabeit** [dtarb/TauDEM#54]
I am trying to run this command in R

`system("mpiexec -n 8 pitremove -z logan.tif -fel loganfel.tif")`

However I get an error message that "the program can't start because gdal111.dll is missing from your computer".

I have installed gdal as administrator and also have added the path to my system variables. I don't see what is missing. I have also installed Rmpi and ms-mpi.

I have installed all packages separately and just downloaded the commandline executables.

**Comment by dtarb** [comment]
The most likely problem is a path.  Use the command 
`where gdal111.dll` 
to see if your system path can find this.

The executables we provide are compiled with ms-mpi.  I do not know whether these are compatible with Rmpi (and my default assumption is that they are not).  If Rmpi is ahead of ms-mpi on your path this may cause a problem, but the error would not be the one you are getting.  
`where mpiexec` will tell you the order of mpi on your system.

**Comment by fabeit** [comment]
ok I tried both commands, it can't find gdal111.dll and where mpiexec returns microsoft HPC pack 2012\bin\mpiexec.exe. So it still can't find gdal111.dll

**Comment by dtarb** [comment]
Since you installed the packages separately there is not much we can do to help.  The fact that `where gdal111.dll` is not finding anything indicates that this is the problem.  The file is not in a location on your path.  Either the GDAL package was not installed, not installed correctly or not installed at a location consistent with the path you added.  You will need to sort this out.  We provided an installer for TauDEM that installs the packages needed and sets up the paths correctly.  Since you did not use this we do not know what is set incorrectly on your system.  If you want to see what the installer does you can look at its source code at https://github.com/dtarb/TauDEM/blob/Develop/WindowsInstaller/setup.iss.
