### ISSUE TITLE
missing gdal111.dll and broken page for downloading

### ISSUE THREAD

**Issue by LaraU** [dtarb/TauDEM#59]
I did a complete Windows install (Version 5.3.4), and I keep getting this error message:  

"The program can't start because gdal111.dll is missing from your computer.   Try reinstalling the program to fix this problem."

I used the recommended Complete Installer.  When I went to download the GDAL 111 individually, it took me to a broken page.  

I've reinstalled with no luck.  Tried using both the command prompt and the ArcGIS toolbox.  Any thoughts?
![image](https://cloud.githubusercontent.com/assets/18150992/14121100/f96d3496-f5c3-11e5-9893-e3dc66a8ae78.png)

![image](https://cloud.githubusercontent.com/assets/18150992/14121115/0f3f86ac-f5c4-11e5-938b-ebda970befd8.png)

**Comment by kornholi** [comment]
This link should work for GDAL: http://download.gisinternals.com/sdk/downloads/release-1600-x64-gdal-1-11-3-mapserver-6-4-2/gdal-111-1600-x64-core.msi

**Comment by LaraU** [comment]
Just tried it, and it's still telling me it can't find the file.

**Comment by pkdash** [comment]
These 2 links should work:
win64: http://download.gisinternals.com/sdk/downloads/release-1600-x64-gdal-1-11-0-mapserver-6-4-1/gdal-111-1600-x64-core.msi
win32: http://download.gisinternals.com/sdk/downloads/release-1600-gdal-1-11-0-mapserver-6-4-1/gdal-111-1600-core.msi

**Comment by pkdash** [comment]
Do you see anything related to gdal in the list of installed programs? Is your OS win32 or 64?

**Comment by LaraU** [comment]
Yes.  It shows up in my programs.  I have Win64.  

C:\Program Files\GDAL

**Comment by LaraU** [comment]
It's funny - the gdal111.dll is in the GDAL folder, but it seems as if the PitRemove tool can't find it when I try to run it.

**Comment by pkdash** [comment]
Do you see 'GDAL 111 (MSVC 2010 Win64)" listed in the list of installed programs?

**Comment by pkdash** [comment]
Also check if windows path includes C:\Program Files\GDAL

**Comment by LaraU** [comment]
Yes to both questions.  The program is installed, and the path is there.

**Comment by dtarb** [comment]
Can you see if TauDEM runs from a command prompt.  At a command prompt type
mpiexec -n 2 pitremove elev.tif 
where elev.tif is the name of your input file.  If this works then we look into something associated with the ArcGIS environment.  If you get the same error then we continue to look into path issues.  What is the result if you type 
where gdal111.dll at a command prompt
If paths are right you should get C:\Program Files\GDAL response.

**Comment by LaraU** [comment]
It seems to run with a command prompt.

![commandpromptrun](https://cloud.githubusercontent.com/assets/18150992/14141865/de6514ac-f64f-11e5-82ee-c43032f4f551.PNG)

When typing the where gdal111.dll it tells me that it could not find the files for the given pattern(s).  But I know the files are there.

**Comment by dtarb** [comment]
That is a bit mysterious.  I would have expected it to either run and find gdal111.dll or not run and not find it together, but not one and not the other.

My next hunch is that your system path is not working right.  Perhaps it is too long or corrupted by an incorrect character.  I suggest at the command prompt type
path  
to see what your path is
path > mypath.txt
to save a copy of what your path is to the mypath.txt file
Then you can follow steps on page 3 in http://hydrology.usu.edu/taudem/taudem5/TauDEM5CommandLineGuide.pdf which is an older help document from TauDEM if you see anything missing that needs editing.  If you can remove (perhaps temporarily) entries that are not necessary, or place c:\Program Files\GDAL close to the beginning it may help.  In editing your path you need to be very careful though, as things like stray spaces can corrupt entries and stop other programs from working which is why a copy to a file is important.  Note that each time you save a path you need to restart any programs that you want to use the new path, i.e. close and re-open the command prompt and ArcGIS.

**Comment by LaraU** [comment]
Ok - I'm looking at my path info, and it seems as if it might be in there twice and it's getting confused.  I am not a programmer, so forgive me if this is a dumb question, but could you tell me which is the correct path?  I see the C:\Program Files\GDAL (which I moved to the front) and C:\GDAL.  Are they both supposed to be there?  Thanks again.

**Comment by LaraU** [comment]
Never mind - success with moving the path to the beginning!  Thanks so much!!

**Comment by dtarb** [comment]
Both are needed.  One is GDAL libraries used by Python and the other GDAL applications.  If you need to know @pkdash could explain what TauDEM uses from each.  I am glad it is working.  Keep a close eye on your system though to be on the lookout for other things that may have been impacted by the path change.
