### ISSUE TITLE
Error Move Outlets to Stream

### ISSUE THREAD

**Issue by sokky41** [dtarb/TauDEM#61]
Hi,
I try to use the Logan demo as explained in the delineating a single watershed and when doing the step "Move Outlet to stream" I get an error referencing: 

ERROR 000714: Error in script MoveOutletsToStreams.
Error in executing: cmd.exe /C C:\PROGRA~1\TauDEM\TAUDEM~2\MOVEOU~1.PY  "logD8Flow.tif" "logD8Contibutesrc.tif" "Outlet_New" "200" "8" "C:\Users\graut\Desktop\CatchmentAnalysis\Examples\Logan\logOutletmv.shp"

Is there some ressource where I can find possible errors explained? So far every now and then single modules chash and I'm often not sure why (I always check for same coordinate systems and sometimes it was just because of the filenamelength)?

**Comment by dtarb** [comment]
In this case I think the problem is that "Outlet_New" does not have a .shp extension.  It should be "Outlet_New.shp".  Unfortunately TauDEM does not trap for this (yet) so fails without indicating the reason and Error 000714 is a general Arcpy error that says the script has failed so would not be that helpful (and is probably listed somewhere on an ESRI website).

There is no one place where errors are explained, because they can occur at many points in the process, sometimes from C++, sometimes from TauDEM python wrappers and sometimes from ArcGIS.  With the TauDEM functions we try to catch and make error messages helpful, but that was not the case here, so sorry.
